### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [Atulhom/react-exercise#2]
Buenas Joan,

Necesito que corrijas esto .

Estas utilizando useState para un constante que no se setea nunca , es un error de concepto grande.

	const [cards] = useState([
		{id: 1, name: 'javascript 1'},
		{id: 2, name: 'card 2'}
	]);

Esto deberia estar asi:

const cards = [ "javascript 1", "card 2"]

Prohibidisimo usar useState sin el seteo, por otro lado utilizas el id para el key del map, no hace falta  que crees un objeto, puedes utilizar el index del map para poner el key en el mapeo tal y como hemos utilizado en clase, solo estas haciendo mas complejo el codigo creando el objeto cards....

Corrige esto y vuelve a subirlo si tienes dudas, me puedes pedir una mentoria.

Saludos.

**Comment by Atulhom** [comment]
Listo, he removido el useState y la ID/Name
